services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Tsf\GatekeeperAiBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Model/'
            - '../src/Installer.php'
            - '../src/TsfGatekeeperAiBundle.php'

    Tsf\GatekeeperAiBundle\Installer:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('TsfGatekeeperAiBundle')"

    Tsf\GatekeeperAiBundle\EventListener\DataObjectListener:
        tags:
            - { name: kernel.event_listener, event: pimcore.dataobject.postDelete, method: onPostDelete }
